### ISSUE TITLE
Recommended approach for header / footer place holders in layout 

### ISSUE THREAD

**Issue by ghost** [gradus/coffeecup#14]
You think its worth implementing that?

https://groups.google.com/forum/?fromgroups#!topic/coffeekup/Bz2BkTjOLXE

**Comment by gradus** [comment]
absolutely.  I would really like to see that implemented.

**Comment by ghost** [comment]
i would take care of that if its alright.

**Comment by gradus** [comment]
@marvin thank you.  I would really appreciate it.  Glad to see see you are on board.

**Comment by ghost** [comment]
its just I dont like when projects i like just die. coffekup/cup is just cool and simple and "one lang to rule them all" :-)

**Comment by gradus** [comment]
Just keeping it alive, b/c I prefer CoffeeCup for templates and use in several projects.  This feature is something I have been wanting for quite some time and has been on the back burner in my mind, so very awesome to see you wanting to tackle it.

**Comment by ghost** [comment]
i want it too and i got everyday an hour so doing something else beside web and game development ^^

**Comment by gradus** [comment]
My time on open source projects is limited to after my day job in the evenings 6:30 EST or weekends when I am not surfing.

**Comment by wmertens** [comment]
@marvin How about reversing the direction? A master template would just has to be a function that takes child templates as arguments and returns a function? Perhaps I'm misunderstanding what you want. I mean something like

``` coffeescript
master = (myTitle, headSection) ->
  ->
    doctype 5
    html lang: 'en', ->
      head ->
        title "#{myTitle} - Site" if myTitle?
        text headSection if headSection?
      body ->
        p 'some content'

childPage = master "Cool title", "I have a head"
```

**Comment by ghost** [comment]
as you might have seen in the google groups thread It wasnt me that wanted that but I said I'll implement it. I am working on something atm let me get back when its done.

**Comment by gradus** [comment]
@marvin @wmertens when you get a chance check out what @twilson63 has done with coffeecup-helpers and creamer.
https://github.com/twilson63/coffeecup-helpers
https://github.com/twilson63/creamer
With these modules we now have some ability to do a lot more with coffeecup as far as template layouts.
I have a boilerplate for flatiron using creamer which allows for me to render a layout and page templates using
`content()` as you would `yield` in rails.

https://github.com/gradus/black-coffee

This is a step in the right direction, I think.
Have discussed in detail the direction of these two projects and will be providing examples in CoffeeCup.
We have thought of adding the helpers to CoffeeCup, but have agreed it is a good idea to keep them separate for now.

**Comment by twilson63** [comment]
FYI,

You can currently do content_for style functionality with creamer, and I
assume it should work with coffeecup native as well, with the `content`
function in creamer, you just section out your template in a consistent
style to your layout.  Here is a spec example:

``` coffeescript
  describe '#attach()', ->
    it 'should allow for content_for style yields', ->
      layout = ->
        html ->
          body ->
            # call content to init your variables...
            content()
            @header() if @header?
            @body()
            @footer() if @footer?
      t = ->
        @header = -> h1 'Header'
        # put your actual template content here
        @body = -> p 'Hello World'
        @footer = -> footer 'Footer'
      output = htmlf """
<html>
  <body>
    <h1>Header</h1>
    <p>Hello World</p>
    <footer>Footer</footer>
  </body>
</html>
      """
      app = new broadway.App()
      app.use creamer, layout: if layout? then layout else null
      app.init()
      app.bind(t).should.equal output
```

check out = https://github.com/twilson63/creamer

For more info.

On Fri, Mar 30, 2012 at 6:06 AM, Kris Windham <
reply@reply.github.com

> wrote:
> 
> @marvin @wmertens when you get a chance check out what @twilson63 has done
> with coffeecup-helpers and creamer
> https://github.com/twilson63/coffeecup-helpers
> https://github.com/twilson63/creamer
> With these modules we now have some ability to do a lot more with
> coffeecup as far as template layouts.
> I have a boilerplate for flatiron using creamer which allows for me to
> render a layout and page templates using
> `content()` as you would `yield` in rails.
> 
> This is a step in the right direction, I think.
> Have discussed in detail the direction of these two projects and will be
> providing examples in CoffeeCup.
> We have thought of adding the helpers to CoffeeCup, but have agreed it is
> a good idea to keep them separate for now.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gradus/coffeecup/issues/14#issuecomment-4839736

## 

Tom Wilson
Jack Russell Software Company   LLC
1067 Cliffwood Drive
Mount Pleasant, SC  29464
Phone: 843-606-0637
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar: http://www.jackhq.com/calendar

**Comment by twilson63** [comment]
You also should be able to implement this in straight coffeecup as well:

``` coffeescript
cc = require 'coffeecup'
layout = ->
  html ->
    body -> 
      content()
      @header() if @header?
      @body() 
      @footer() if @footer?
template = ->
  @header = -> header 'Foo'
  @body = -> body 'Bar'
  @footer = -> footer 'Baz'

hardcode = content: template
console.log cc.render(layout, hardcode: hardcode)
```

should output

``` html
<html>
  <body>
    <header>Foo</header>
    <body>Bar</body>
    <footer>Baz</footer>
  </body>
</html>
```
