### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by gradus** [gradus/coffeecup#15]
I would like to switch the tests to mocha and a bit better test coverage.

**Comment by twilson63** [comment]
Agree, that will be fun, mocha is awesome!

On Fri, Mar 30, 2012 at 7:00 AM, Kris Windham <
reply@reply.github.com

> wrote:
> 
> I would like to switch the tests to mocha and a bit better test coverage.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gradus/coffeecup/issues/15

## 

Tom Wilson
Jack Russell Software Company   LLC
1067 Cliffwood Drive
Mount Pleasant, SC  29464
Phone: 843-606-0637
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar: http://www.jackhq.com/calendar

**Comment by gradus** [comment]
creating `testing` branch for the tests if you would like to contribute

**Comment by gradus** [comment]
make that branch name `tests`

**Comment by twilson63** [comment]
Started adding some tests, oops for got to add to the testing branch, sorry

**Comment by gradus** [comment]
No worries. The testing branch can be merged in to master at this point.  I will be back on later this afternoon.  Thanks for all of your work and wonderful advice.

**Comment by gradus** [comment]
@twilson63 nice work so far on the mocha tests.
I set the mocha version to 1.0.0 in package.json
I am going to scrap the `tests` branch
no reason we can't do this in master

**Comment by gradus** [comment]
@twilson63 you should be able to now run the mocha tests with `npm test`
As soon as we are sure we have adequate test coverage, I will clean up the cake file a bit and have these tests run with `cake test`.  Currently `cake test` will run the test.coffee.

**Comment by gradus** [comment]
Added quite a few more tests and travis.yml
Build passes on node v0.6 and v0.7
had to add the compiled js in lib to get this to work.

**Comment by twilson63** [comment]
Cool Beans!

Sent from my iPhone

On Mar 31, 2012, at 2:31 PM, Kris Windham
reply@reply.github.com
wrote:

**Comment by gradus** [comment]
At this point we have 31 passing tests with mocha.
We are just missing the IE conditional test, Auto Escaping, and the coffeescript helper function test.
Add those three and we will have the same test coverage with mocha as in the test.coffee file.

**Comment by twilson63** [comment]
Did you add a travis build badge to the readme?  

```
[![build status](https://secure.travis-ci.org/twilson63/creamer.png)](http://travis-ci.org/twilson63/creamer)

```

**Comment by gradus** [comment]
The build status is displaying in the readme for CoffeeCup on github.

Just a little more work and we will have a clean set of mocha tests that will run with npm test.
Then I will remove the old tests and clean up the cakefile a bit.

**Comment by twilson63** [comment]
Looks good!

Sent from my iPhone

On Mar 31, 2012, at 8:12 PM, Kris Windham
reply@reply.github.com
wrote:

**Comment by gradus** [comment]
@twilson63 all of the mocha tests are there to cover the existing tests in test.coffee with the exception of `CoffeeScript helper (function )` in coffeescriptHelper.coffee.  The test is there, but commented.  It should work, but for some reason I am struggling to get it to pass.  Would you take a look and see if you can figure out why?

**Comment by gradus** [comment]
removed old tests excepting benchmark test and updated cakefile

**Comment by gradus** [comment]
All existing tests have been rewritten in mocha.  Some could use a little refactoring and there are a couple duplicates, but the issue has been resolved I believe.
