### ISSUE TITLE
Add Creamer flatiron examples

### ISSUE THREAD

**Issue by gradus** [gradus/coffeecup#16]
Need to add examples for creamer and flatiron usage

**Comment by twilson63** [comment]
Added single page example, the views and mvc example needs a new release of director in flatiron, as soon as it is released I will create an example.

**Comment by gradus** [comment]
Thanks @twilson63 looks good.

**Comment by twilson63** [comment]
Just added the views example, which should show how to use creamer to render coffeecup views from a views folder.

**Comment by gradus** [comment]
You are the man.

**Comment by twilson63** [comment]
Added an mvc example as well.  in the readme shows the only main issue is that creamer depends on the master version of director.  But the Controller Model layout looks pretty good to me, what are your thoughts?

**Comment by gradus** [comment]
I think the examples look great. MVC example is perfect. I am going to go ahead and close this issue and we can update the mvc readme and package.json when the new version of director is released.

**Comment by twilson63** [comment]
I updated the package.json to use my fork of flatiron to pull in the latest director. So it should work for anyone who tries to use it.
