### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by wmertens** [gradus/coffeecup#18]
So Coffee[KC]up is amazing, the one thing I miss from Jade is Markdown support.

I tried just including it as a helper function but haven't had much luck. Any thoughts on how to make that work?

**Comment by gradus** [comment]
What I would like to see in CoffeeCup is something like this.

``` coffeescript

markdown, ->
  [This is a link to markdown](http://daringfireball.net/projects/markdown/)
  `here is a block`
  **this is bold**

```

Sounds like a fun Saturday project.  
I might be able to tackle this over the weekend as I love markdown and would like to see this working as above.
Thanks for the inspiration.

Alternatively, you could find a markdown module and add the parse method to the coffeecup template's context.
I was successful in using [node-markdown](https://github.com/andris9/node-markdown) in slightly different way for this but it is old and I had to hack it to work correctly.
I did not bother to push a demonstration of the slop I created to github.

Let's see what we can do with adding markdown support as demonstrated above or if there are any other suggestions of implementing, I am open.

**Comment by gradus** [comment]
On second thought, as much as I like MarkDown and could see it baked in to CoffeeCup,
I think our intent should be to try and keep CoffeeCup as pure as possible and implement plugins for features like this.

@twilson63 suggested something like the following for how it could be implemented.

```
cc = require 'coffeecup'
ccmd = require 'coffeecup-markdown'

cc.use ccmd

cc.render ->
  md -> [a link](http://foo.com)

```

**Comment by wmertens** [comment]
I agree that markdown support makes it less pure. On the other hand I like writing static HTML do that etags and caching work optimally. This also means that I like to use the coffeecup compiler to compile down to HTML so the static provider handles that. 

In other words, I would like an easy way to specify which plugins a certain template needs, preferably in the template itself. Thoughts?

Alternatively, perhaps something like connect-assetmanager makes compiling to file unnecessary. I haven't found one that I like yet though. Ideally I'd want a middleware that automatically compiles templates and minimizes http requests by combining script tags (inlining them for small scripts), handling etags etc, all without explicit configuration. I digress :)

**Comment by gradus** [comment]
@wmertens I really appreciate you throwing your ideas out and trying to be a part of helping make this a better project.

I see your point and how that could be useful.  I am not sure that specifying plugins in the template itself is the way to go.

Have you taken a look at how @twilson63  is using CoffeeCup with flatiron and creamer or the coffeecup-helpers project?
Please do so, if not.  He and I are really on the same page with keeping features out of CoffeeCup, making it as pure as possible and making it pluggable for anyone to write features as independent pieces of software.

**Comment by aseemk** [comment]
I'd love to see Markdown support as well. I think it's one of those few formats that's become so ubiquitous now (because it's so useful) that it makes CoffeeCup more appealing to newcomers when it "just works" with awesome stuff like Markdown and Stylus.

One q on Syntax -- how would your examples be valid CoffeeScript? E.g. this:

``` coffee
markdown, ->
  [This is a link to markdown](http://daringfireball.net/projects/markdown/)
  `here is a block`
  **this is bold**
```

The `[This is a link to markdown]` won't be valid CoffeeScript, nor will the "function call" after that with the URL without quotes. Etc.

Wouldn't/couldn't the Markdown just be wrapped in a multi-line string?

``` coffee
markdown, -> '''
  [This is a link to markdown](http://daringfireball.net/projects/markdown/)
  `here is a block`
  **this is bold**
'''
```

I know Stylus-in-CoffeeCup doesn't need to be wrapped in a multi-line string, but that has compatible syntax. Just a suggestion.

**Comment by twilson63** [comment]
@aseemk I agree with you that it would be a multi-line string:

``` coffeescript
markdown '''
 # Header One

* List 1
* List 2

[link](url)

'''
```

---

The question I continue to ask, is should coffeecup have so many dependencies and potentially remove itself from browser compatibility?  I think there should be a way to have a plugin system like Broadway [https://github.com/flatiron/broadway](https://github.com/flatiron/broadway) to include mixins like stylus, markdown, github-markdown, etc

Thoughts?
