### ISSUE TITLE
Misc visibility issues

### ISSUE THREAD

**Issue by wmertens** [gradus/coffeecup#19]
- The easydoc refers to the `coffeekup_` Google group which doesn't exist. Should it be `coffeekup`?
- Your coffeekup fork could point to coffeecup in its readme so people can find it more easily. It took me a while to find coffeecup.
- Your easydoc could embed an example like http://coffeekup.org does.

**Comment by gradus** [comment]
The Readme for the project has the correct googlegroup link

https://groups.google.com/forum/#!forum/coffeecup_

I need to update easydoc.org.  Thanks for pointing that out.

I agree it is difficult to find.

I always google something like `<project name> github` when looking for a specific project.

**Comment by gradus** [comment]
Actually, I have already updated the google group link on easydoc.org.

**Comment by gradus** [comment]
High visibility has it's disadvantages.

I would love to have more contributors on board and folks that are willing to write plugins for CoffeeCup.
On the other hand, I do not have a desire to have too many feature requests and people complaining about how it is not like some other templating system like jade that they have used.  If you want jade, use jade.  
CoffeeCup is pretty freakin' awesome, though.

I would like to see this project stay smaller for a little while.
If it is meant to be, it will gain traction and the right people will find it.
