### ISSUE TITLE
update to coffeescript 1.3.1

### ISSUE THREAD

**Issue by gradus** [gradus/coffeecup#25]
currently locked to coffeescript v1.2.0 in package.json
b/c 1.3.1 breaks the build
We need to be able to upgrade to 1.3.1

**Comment by asalant** [comment]
+1

At least one issue here is that 'yield' (defined by coffeecup) is a reserved keyword that causes strict mode to fail.

**Comment by gradus** [comment]
Thanks. That is definitely one of several issues, but the most prominent one I've noticed.

**Comment by gradus** [comment]
@rsimoes took care of switching `yield` to `cede`.  I have updated the tests to reflect the new var and the build no longer breaks with 1.3.1.  I have an app successfully funning with the master branch of coffeecup and coffeescript 1.3.1.  Please chime in if you find any further issues with 1.3.1 that I might not have noticed.
