### ISSUE TITLE
Error compiling switch statement

### ISSUE THREAD

**Issue by srackham** [gradus/coffeecup#26]
I get the following error when compiling the example template, looks like the 'switch' reserved word being declared as variable. Here's a snipped from the example:

```
$ cat t2.coffee
switch @user.role
  when 'owner', 'admin'
    li -> a href: '/admin', -> 'Secret Stuff'

$ ./bin/coffeecup t2.coffee

undefined:2
var a,i,li,ol,s,th,u,hr,switch,use;a = function(){return __cc.tag('a', argumen
                        ^^^^^^
SyntaxError: Unexpected token switch
    at Object.Function (unknown source)
    at Object.compile (/home/srackham/projects/coffeecup.git/lib/coffeecup.js:333:10)
    at Object.render (/home/srackham/projects/coffeecup.git/lib/coffeecup.js:354:21)
    at /home/srackham/projects/coffeecup.git/lib/cli.js:28:26
    at [object Object].<anonymous> (fs.js:123:5)
    at [object Object].emit (events.js:64:17)
    at Object.oncomplete (fs.js:1181:12)

$
```

**Comment by gradus** [comment]
I just made a fix and bumped to version 0.3.10
Try using the new version and let me know if that fixes your problem.

**Comment by gradus** [comment]
`switch` is an SVG 1.1 tag
I removed switch from that list of elements.
SVG support for `switch` seemed to me to be less important than the use case in your snippet.

**Comment by twilson63** [comment]
What version of coffee-script are you using?

Sent from my iPhone

On Apr 14, 2012, at 7:52 PM, Stuart Rackham
reply@reply.github.com
wrote:

**Comment by gradus** [comment]
It's locked in to 1.2.0 as we have some problems with 1.3.1 that need to be addressed before supporting it with CoffeeCup.

**Comment by gradus** [comment]
@twilson63 did you mean 'what version of CoffeeCup..?'
pretty sure @srackham is using the latest as he is the one who prompted the latest release with the Stylus support addition.

**Comment by twilson63** [comment]
No, what version of coffee-script, just assuming that might be the
problem.  Looks like you got it!

Sweet!

Sent from my iPhone

On Apr 14, 2012, at 8:38 PM, Kris Windham
reply@reply.github.com
wrote:

**Comment by srackham** [comment]
That's fixed it.
Thanks for the super-quick response.
