### ISSUE TITLE
precompilation options

### ISSUE THREAD

**Issue by ilogico** [gradus/coffeecup#32]
I tried coffeecup because coffeekup cli wasn't working.
I was interested in precompiling the templates so I explored the options.

I wanted to be able to compile templates into a single file so I wrote a very simple patch, but I don't know how to commit it.
I'll read the git docs, but I would like to know if it's OK, or generally just get feedback from someone.

Switches --bare and --core seem to be ignored completely by the cli and I'm not sure how they should work. Currently, all the templates are added to the chosen namespace, each one declaring either the entire renderer or just the functions they need if the -z is used. It would be nice if we could reduce the output size as much as we could, but I feel I have to touch the compiler itself to achive that.

In general, I think the cli is a bit messy and inflexible, but I would just like to have some feedback before getting my hands too dirty.

**Comment by gradus** [comment]
This project is open source and getting your hands dirty and contributing is fully encouraged.
If you have something that works and good justification for doing it, there is a good chance we can get it pulled into the project.
Based your comments, I am a little uncertain what you would like to do with the compiler, but certainly would love to have a look at your ideas
Just let me know if you need some help in using git to fork the project, make your changes, commit them and submit a pull request.

**Comment by ilogico** [comment]
Since I'm now compiling multiple templates in one JavaScript file, I wanted to save space by not repeating the declaration of the helper functions in all templates. It's not a big deal because with the -z option, the only helpers seem to be the 'text', 'h' and 'cede', which are quite small.

I think I committed the changes. I still didn't fix the -w option to work with multiple files, which I plan on doing next so I don't have to manually recompile the templates all the time. I think it only works with one file at the time for the moment (I mean, I think it doesn't watch directories) so there's no risk of breaking anything.

**Comment by gradus** [comment]
Thanks.  Will have a look when I have a moment.
