### ISSUE TITLE
Express 3.x support

### ISSUE THREAD

**Issue by shimaore** [gradus/coffeecup#36]
Express 3 expects a member called `__express` with a profile `(path, options, callback)` where the callback has a profile of `(err,str)` ([reference](https://github.com/visionmedia/express/blob/master/lib/application.js#L141)).

This could be for example (modeled after `coffeecup.render` and [consolidate.js](https://github.com/visionmedia/consolidate.js/blob/master/lib/consolidate.js#L50)):

```
coffeecup.__express = (path, options = {}, fn) ->
  if not window?
    options.stylus = require 'stylus'

  if options.cache and cache[path]?
    tpl = cache[path]
    fn null, tpl(options)
  else
    fs.readFile path, 'utf8', (err, str) ->
      if err then return fn err
      tpl = coffeecup.compile(str,options);
      if options.cache then cache[path] = tpl
      fn null, tpl(options)
```

This would be helpful in zappajs where we use coffeecup as the default engine.

Some related questions (feel free to move to separate issue): I'm not sure what to do wrt `coffeecup.adapter.express`, which is also use by zappa (zappa might be the only user for that feature?). Since not everyone is using Express 3.x yet it makes sense to keep it for now. However I'm curious whether there's a special reason `partial` is only available there (and not in generic CoffeeCup). Finally the `TemplateError` bits could be added to the `__express` function and use the `err` parameter of the callback, in Express 3.x.

**Comment by gradus** [comment]
@Akkuma your work looks good, thanks, but I do not want to break compatibility with Express 2.  I will address this issue when Express 3 moves out of beta and becomes more widely used.

**Comment by gradus** [comment]
thanks @shimaore
