### ISSUE TITLE
Falsy values for attributes are skipped

### ISSUE THREAD

**Issue by fson** [gradus/coffeecup#38]
This template

``` coffeescript
select ->
  for i in [0..2]
    option value: i
```

compiles to

``` html
<select>
  <option></option>
  <option value="1"></option>
  <option value="2"></option>
</select>
```

Notice missing `value="0"`.

**Comment by ilogico** [comment]
```
select ->
  for i in [0..2]
    option value: i.toString()
```

This should work. I don't know what's the desired behaviour.

**Comment by gradus** [comment]
yes.  0 for value gives you `<option></option>`
That is not the desired behavior. Thanks for reporting this.

**Comment by gradus** [comment]
The latest version (v0.3.15) of CoffeeCup should fix this issue.

**Comment by fson** [comment]
Thanks!
