### ISSUE TITLE
explicit require of coffee-script

### ISSUE THREAD

**Issue by twilson63** [gradus/coffeecup#4]
In order to use the new coffeecup module in flatiron, I had to first require 'coffee-script'

``` coffeescript
require 'coffee-script'
ccup = require 'coffeecup'
```

The old coffeekup would implicitly require coffee-script

``` coffeescript
ccup = require 'coffeekup'
```

**Comment by gradus** [comment]
This issue should be resolved with the latest version of coffeecup v0.3.5-2
Have tested with iron-coffee app as demonstrated here:

  https://github.com/gradus/black-coffee
