### ISSUE TITLE
Attributes with numeric value 0 (zero) are not rendered

### ISSUE THREAD

**Issue by nilskp** [gradus/coffeecup#42]
E.g. when passing a variable with a numeric value of 0, the colspan attribute is not rendered:

```
td colspan: @colspan, "Hello"
```

BTW, this also happens on the original CoffeKup.

**Comment by gradus** [comment]
thanks for letting me know.  Will get this fixed when I have a moment.

**Comment by gradus** [comment]
I am not able to recreate this issue.  There was a monkey patch implemented to address Issue #53 that may have fixed this problem.  Are you still experiencing the issue?  If so, can you supply a more specific example of when this is happening?
