### ISSUE TITLE
coffeecup and express3

### ISSUE THREAD

**Issue by joques** [gradus/coffeecup#46]
Hi all,
saw that Coffeecup was updated for express 3 in #39. But, I can't seem to find the right syntax to bind a view engine in express 3 to Coffeecup. Could you update the README or the example/express plz
José

**Comment by ramstein74** [comment]
same here

app.set 'view engine', 'coffee'
app.register '.coffee', require('coffeecup').adapters.express
app.get '/', (req, res) ->
  # Will render views/index.coffee:
  res.render 'index', foo: 'bar'

i got the error:
object function app(req,res){app.handle(req,res);} has not method 'register'

**Comment by joques** [comment]
the actual syntax is 

<pre><code>app.engine 'coffee', require('coffeecup').__express</code></pre>

This works for me

**Comment by gradus** [comment]
Updated the README and the express example.
