### ISSUE TITLE
option value: '' throws out value

### ISSUE THREAD

**Issue by danschumann** [gradus/coffeecup#53]
this was an issue with the old coffeekup, does it still apply?  

Doing 

```
option value: '', 'title'
```

 creates 

```
<option>title</option>
```

 instead of 

```
<option value="">title</option>
```

is there a way to set a blank string as a value?

**Comment by danschumann** [comment]
I've confirmed it is still a bug that makes it basically unusuable..
I'll be monkey patching line 167 of the .js file was

```
} else if (v || v === 0) {
```

can be

```
} else if (v || v === '' || v === 0) {
```

**Comment by gradus** [comment]
monkey patched fixed issue
