### ISSUE TITLE
Haml ▸ HTML ▸ Coffeecup ▸ Javascript ▸ CoffeeScript Converter!  

### ISSUE THREAD

**Issue by mikesmullin** [gradus/coffeecup#55]
none of the links found under your README.md for tools > html 2 coffeecup converters were working for me. 

what i really wanted was an online tool i could bookmark and run in my browser. something that would translate haml to coffeecup (moving from rails to node).

so i made this:

http://haml-html-coffeecup-javascript-coffeescript-converter.smullindesign.com/

or, if above doesn't work:

http://mikesmullin.github.com/haml-html-coffeecup-javascript-coffeescript-converter/

since it is hosted by github it shouldn't go down and its easy to fork mirrors.

you may wish to update your readme.md with this all-in-one tool.

**Comment by alist** [comment]
This is cool. Did you make a pull request?

**Comment by mikesmullin** [comment]
ah no i should have done that. will try it now
