### ISSUE TITLE
How To Refactor Right?

### ISSUE THREAD

**Issue by globalworming** [gradus/coffeecup#59]
Hi

I am trying to refactor my code from 

``` javascript
div  ->
  h2 'Heading'
    div ->
      MoreStuff
```

to 

``` javascript
example = (headerText, stuff) ->
  div  ->
    h2 headerText
      div ->
        stuff
```

but

``` javascript
example 'Header', text 'ExampleText'
```

renderes to 

```
ExampleText<div>
  <h2>RefactoredCode</h2>
  <div>
  </div>
</div>
```

though I expected it to be

```
<div>
  <h2>RefactoredCode</h2>
  <div>
    ExampleText
  </div>
</div>
```

Could somebody please tell me how to do it right? I could not find an answer to that in the docs. Or is refactoring this way not possible? Then it may be a real issue^^
Help is greatly appreciated.

Regards
Andreas Worm

**Comment by wmertens** [comment]
Try

example 'Header', -> text 'ExampleText'

Note the function call.

I'm still trying to think of ways to allow direct invocation as well as in-function calls… Perhaps returning objects that only respond to .toString() once, and pushing it on the results as well as returning them…

Wout.

**Comment by globalworming** [comment]
Thanks for your response

but unfortunately the "text 'ExampleText'" does not produce any html output at all. Sorry ..
I tried around a bit, but nothing seems to work as expected.
Do you can think of some other syntax which could work?

**Comment by wmertens** [comment]
When I use

```
example = (headerText, stuff) ->
    div  ->
      h2 headerText
      div ->
        stuff()

example 'Header', -> text 'ExampleText'
```

it renders to

```
<div><h2>Header</h2><div>ExampleText</div></div>
```

So you had to call stuff(). You can also write "do stuff" if you prefer.

Wout.

**Comment by globalworming** [comment]
Yeah! 

Thanks, really! 

I missed that call stuff stuf :)
