### ISSUE TITLE
Method of compiling template that references Javascript library to HTML?

### ISSUE THREAD

**Issue by lorensr** [gradus/coffeecup#63]
If this is my template:

```
Foo =
 bar: 'Hi'
text Foo.bar
```

compiling to HTML works fine:

```
me$ coffeecup test.coffee
me$ cat test.html
Hi
```

But if I reference a Javascript library:

```
class Foo extends Backbone.Model
  @bar: 'Hi'
text Foo.bar
```

I get:

```
undefined:283
})(Backbone.Model);
   ^
ReferenceError: Backbone is not defined
```

Is there a way of doing this already that I am not aware of? Thanks!

**Comment by wmertens** [comment]
If you want to do that you have to pass backbone into the scope when
executing the function or else you need to use
https://github.com/jaekwon/coffeemugg

**Comment by lorensr** [comment]
So I can't use the `coffeecup` executable? So I should do something like this on the server?

``` coffeescript
Backbone = require 'backbone'

class Foo extends Backbone.Model
  bar: 'Hi'

template = ->
  text Foo.bar

cc = require 'coffeecup'
console.log cc.render(template, {}, { locals: { Foo: Foo, Backbone: Backbone } })
```

followed by 

```
coffee -bc test.coffee
node test.js
```

(I'm doing something wrong since that gives: 

```
/Users/me/Documents/code/ferro/test.js:4
unction ctor() { this.constructor = child; } ctor.prototype = parent.prototype
                                                                    ^
TypeError: Cannot read property 'prototype' of undefined
```

)
Or does it have to be done in the browser, increasing load time:

``` html
<html>
<script src="extension/js/vendor/underscore.js"></script>
<script src="extension/js/vendor/jquery.js"></script>
<script src="extension/js/vendor/backbone.js"></script>
<script src="node_modules/coffeecup/lib/coffeecup.js"></script>
<script src="template.js"></script>
<script>
  $(function() {
    $('body').append(coffeecup.render(template, {}, { locals: { Foo: Foo, Backbone: Backbone } }));
  });
</script>
<body>
</body>
</html>
```

This gives a similar error in the JS console:

```
Uncaught TypeError: Cannot read property 'prototype' of undefined template.js:4
Uncaught TypeError: Cannot call method 'indexOf' of undefined coffeecup.js:389
```

Thanks again for your help :)

**Comment by wmertens** [comment]
Actually if you want to compile to static html you just need to require the backbone library in your template.

An alternative is compiling to js and then loading it after loading backbone.

You can also pass backbone via the data, by doing "extends data.Backbone.model".

Wout.

**Comment by lorensr** [comment]
> Actually if you want to compile to static html you just need to require the backbone library in your template.

Going back to the original Backbone template and requiring the library doesn't work because unlike Node, the `coffeecup` executable doesn't recognize `require`: 

``` coffeescript
Backbone = require 'backbone'

class Foo extends Backbone.Model
  @bar: 'Hi'
text Foo.bar
```

```
me$ coffeecup test.coffee

undefined:271
Backbone = require('backbone');
           ^
ReferenceError: require is not defined
    at Object.eval (eval at <anonymous> (/usr/local/share/npm/lib/node_modules/coffeecup/lib/coffeecup.js:410:10))
    at eval (eval at <anonymous> (/usr/local/share/npm/lib/node_modules/coffeecup/lib/coffeecup.js:410:10))
    at Object.coffeecup.render (/usr/local/share/npm/lib/node_modules/coffeecup/lib/coffeecup.js:443:10)
    at compile (/usr/local/share/npm/lib/node_modules/coffeecup/lib/cli.js:94:26)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

> An alternative is compiling to js and then loading it after loading backbone.

This as well as the first example in my most recent comment above work fine, thanks! (I was missing an @ before the bar definition.)
