### ISSUE TITLE
webview tag doesn't work

### ISSUE THREAD

**Issue by alexchandel** [gradus/coffeecup#76]
This is similar to #75. `webview` is a custom tag used in Chrome Packaged Apps. Apparently Google likes to use custom tags, so there should be a CoffeeCup means to generate arbitrary tags from certain unknown function.

There should be a builtin way to register unrecognized symbols as tags in CoffeeCup, either with C-preprocessor syntax or a builtin function:

``` CoffeeScript
##register(webview)
div ->
    webview ->

coffeecup(tag: 'webview')
div ->
    webview ->
```

**Comment by 10xLaCroixDrinker** [comment]
[Custom tags are supported](https://github.com/gradus/coffeecup/blob/master/test/custom.coffee)
