### ISSUE TITLE
Jade-like block inheritance?

### ISSUE THREAD

**Issue by randallb** [gradus/coffeecup#8]
I really like the idea of block-style inheritance.

https://github.com/visionmedia/jade#a6-7

Given that Express v3 is doing away with layouts, these block styles could really work well in a lot of cases. Especially when you're doing a blog... you could append to a posts block, and the permalink container could pick its own layout.

Is this something you'd want to see in Coffeecup? Does it feel "pure"? If so, I might give a crack at putting something together.

**Comment by gradus** [comment]
I am not sure how 'pure' that idea feels, but it is definitely something worth considering as a feature

**Comment by randallb** [comment]
Ideally, I'd like it if we could try to structure github issues in a way that lets people know what we're working on, etc.

Do you have an idea for the next milestone you'd like to get out? Any overarching ideas you'd like to see implemented?

**Comment by gradus** [comment]
Not at the moment.
Just want to keep the project alive.

I am open to suggestions.
Let me give it some thought when I have a free moment and we can get organized.
I am just glad some one else is on board with me to keep CoffeeCup alive.

**Comment by gradus** [comment]
@randallb The idea of block-style inheritance seems like it might work if you want to roll it out.
As far as milestones, I think improving error reporting is probably first on my agenda, but I have not yet come up with a game plan.  Then, watching the directories like Jitter might be nice.  I am hoping more people will come on board and help out as I am working on a number of projects ( mostly closed source with my FT gig ) at the moment, but I really wanted to keep this one going.  I can add you as a collaborator if you think you have the time to really be involved in this project.

**Comment by randallb** [comment]
@gradus I'm in a similar situation as you are, so I figure I could at least try to be as involved as you. I haven't looked at the source (at all) yet, but I'm interested in giving it a go.

**Comment by gradus** [comment]
@randallb added you as a collaborator if you feel comfortable with it.

**Comment by gradus** [comment]
@randallb please study the code in depth before making commits and make sure all tests are passing. I've set up a docs site at http://easydoc.org/coffeecup  (needs a little work ), but let me know if there is anything I can add to make it a little better.  Let's take the time to make this code awesome.  I see a lot of little things that need to be done.  Not sure if I will add as issues or just do it.

**Comment by randallb** [comment]
I'm going to probably add issues / pull requests for now.

Just an FYI- I'm currently on vacation through early next week, so I'll get to work probably middle of next week.

**Comment by gradus** [comment]
Sounds great to me.  My plate is pretty full, so this is not a priority project for me.  I will not be putting any work into CoffeeCup until next week either.  I am glad to put whatever time it takes in the future to maintain, though.  Pretty dedicated to keeping this going to use in further projects.  Working on a flatiron http boilerplate that is 100% coffee that I want to use this for.  https://github.com/gradus/black-coffee.  I like the idea of coffeescript on the server and client and templates written in coffee-script.  One language to rule them all.

**Comment by ghost** [comment]
i am on board too though :) i really liked jade but since coffeecup I am off anything else and as gradus said ... on lang to rule them all ^^

by the way block inheritance would be a great feature.

**Comment by randallb** [comment]
I'm removing myself from this project as my company is switching to jade. :(

**Comment by gradus** [comment]
That's too bad.  Just reviewing some ideas this morning using https://github.com/twilson63/coffeecup-helpers that are sweet!
I am getting very excited about the future of CoffeeCup.

**Comment by wmertens** [comment]
So I don't understand what the difference is between https://github.com/visionmedia/jade#a6-7 and

``` coffeescript
ul ->
  li ".first", -> a href:"#", "foo"
  li -> a href:"#", "bar"
  li ".last", -> a href:"#", "baz"
```

?

**Comment by gradus** [comment]
@wmertens I really see no difference.
Closing this issue.

**Comment by gradus** [comment]
@wmertens actually, there is a minor difference, but that only has to do with my preference for writing markup as coffeescript.  Not really a big fan of jade after months of experimenting with it.

**Comment by randallb** [comment]
https://github.com/visionmedia/jade#a11

That's actually what i'm talking about. Block style inheritance, not block expansion. Specifically the "extends" keyword.

**Comment by randallb** [comment]
Regardless, it's a feature.

**Comment by gradus** [comment]
@randallb I know what you mean.  I can reopen this issue if anyone else that is using it sees it to be an important feature? 
I hope you will continue to use CoffeeCup even though I know you mentioned switching to jade.
I prefer CoffeeCup.
You should check out what @twilson63 is doing with CoffeeCup, creamer and coffeecup-helpers.

**Comment by gradus** [comment]
@randallb I did close this issue for now, b/c I want to focus on making CoffeeCup as pure as possible, but pluggable for any features that want to be built independently.  I really believe that is the intent.

**Comment by aseemk** [comment]
Having just come across CoffeeCup, first of all -- thank you so much for your effort in keeping CoffeeKup alive! It's greatly appreciated.

I wanted to chime in a _massive_ +1 for this feature -- both because I've been wanting first-class block support in views in general, but also because Express 3 will _require_ views to have it -- it's getting rid of layouts and saying views should implement them instead.

I think this is an extremely important feature. I would guess that CoffeeCup won't be usable as a view language on Express 3 without it -- layouts and partials are such a common requirement.

But Jade does it even better by supporting arbitrary blocks. This is really useful for having e.g. a stylesheets block at the top and a scripts block at the bottom.

Would love to see this! I'm happy to help with design and maybe even implementation, but I would need to ramp up a bunch on the CoffeeCup implementation before I can be effective there. =)

Thanks again for the great work and consideration!

**Comment by twilson63** [comment]
I think coffeecup will work fine with Express 3, if not, I feel confident we will all work to close any gaps.  As far as block style inheritance, since it is just coffee-script, you can do a lot of the the same inheritance style as jade using the hardcode helper feature:

``` coffeescript
cc = require "coffeecup"

layout = ->
  doctype 5
  html ->
    head if blockHead? then blockHead else ->
      title 'foo'
    body if blockBody? then blockBody else ->
        h1 'foo bar baz'

console.log(cc.render layout, formatted: true)

foo = cc.render layout, 
  hardcode:
    blockHead: ->
      title 'BAM!'
    blockBody: ->
      h1 'BAM BEEP BOP'

console.log foo
```

## renders

``` html
<!DOCTYPE html>
<html>
  <head><title>foo</title></head>
  <body><h1>foo bar baz</h1></body>
</html>

<!DOCTYPE html>
<html>
  <head><title>BAM!</title></head>
  <body><h1>BAM BEEP BOP</h1></body>
</html>

```

**Comment by aseemk** [comment]
Hey Tom, I didn't mean to say that CoffeeCup won't work with Express 3 -- I meant that it won't be useful.

A realistic Express use case doesn't have the partials/layouts/etc. in the same file -- the purpose of a partial is to share reusable components across views. Similarly, the purpose of a layout is a common container for views.

Given that, how would a view reference a partial and a layout in separate files using today's CoffeeCup?

**Comment by wmertens** [comment]
Coffeecup templates are just functions, which you can require as a module. 

I'm not familiar with the express 3 partials, could you point to a good example to translate into coffeecup?

**Comment by twilson63** [comment]
Hey @aseemk 

CoffeeCup IMO works very much like the block inheritance style of jade, using the helpers feature or coffeecup.  You can simply pass in your inherited blocks as functions on the hardcode object, and you can go as deep as you want, as far as separate files, as @wmertens mentions above, you can require them as modules, I have tried to show you a simple example here:  https://gist.github.com/2463910

After working through some use cases, there may be a sugar feature that is worth discussing further:

# Block Helper

A block helper is a function in coffeecup that takes two parameters:
- blockName - block function name - string
- defaultFunction - default function if the above function is not defined

### example

``` coffeescript
html ->
  block 'head', -> 
    title 'Foo'
  block 'body', ->
    h1 'Body Foo'
```

## Now when the user renders the template, they can just include or not include the block helper functions on the hardcode key

``` coffeescript
cc.render view, hardcode: { head: -> title 'Index', body: -> h1 'Awesome' }
```

## We could come up with a better name for the hardcode key....

``` coffeescript
cc.render view, blocks: { head: -> title 'Index', body: -> h1 'Awesome' }
```

Thoughts???

**Comment by gradus** [comment]
Just wanted to voice my opinion in this discussion.
Though I appreciate what express can do and all of the hard work that has gone into it, I am still not a big fan.
I think jade is probably your best option if you want to use express.  I am a much bigger fan of flatiron or tako.
My goal is to keep CoffeeCup as simplistic as possible and not try to accomplish everything that jade does.
At this point, it really is not intended for use with Express, but can most certainly be.  Please check out the flatiron and tako frameworks when you have a chance.  I think you will be impressed with how decoupled things should be.  the less baked in, the better in my opinion.
@twilson63 thanks for the examples, ideas and helping with communication as I have been out of commission over the past weekend.  I like your idea expressed with the block helper above.

**Comment by gradus** [comment]
The following is a boilerplate for the personal direction I am experimenting with using a stack of CoffeeCup, Flatiron and Creamer, written in CoffeeScript.
http://easydoc.org/blackcoffee

The examples Tom has included for flatiron and creamer are also excellent, though the latest needed patch to flatiron/director has yet to be published.
I am using a tarball of @twilson63's fork of flatiron, installing creamer locally, bundling the flatiron and creamer dependencies and deploying to nodejitsu.
http://black-coffee.jit.su

@twilson63, I lke the idea of using broadway for plugins.
I believe Markdown support, Stylus support and any other puggable components should be a standalone modules.

In addition having a look at the idea @twilson63 put out in this is gist is worth a read

https://gist.github.com/14bc67ef8defec281d58

Tako - CoffeeScript - CoffeeCup

**Comment by tpisto** [comment]
+1 for https://github.com/visionmedia/jade#a11  like feature.
